# This workflow will run semver.pl and update the versions.json file in the root folder.
# The version.jsonfile is then added, commited and pushed to the current branch.

name: semver patch
#name: Houston Service - semver workflow

on:
  push:
    branch-excludes: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract current branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch
    - name: Echo Branch Name
      shell: bash
      run: |
        echo Branch name: ${{ steps.extract_branch.outputs.branch }}
    - name: Echo environment
      shell: bash
      run: |
        env
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "${GITHUB_WORKSPACE}"
        echo "GITHUB_EVENT_PATH"
        cat "${GITHUB_EVENT_PATH}"

    - uses: actions/checkout@v2
      with:
        repository: stugit/actions
        path: actions
        fetch-depth: 0
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
#    - name: Install dependencies
#      run: |
#        cd "${GITHUB_WORKSPACE}/actions"
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
    - name: run semver, store in step variable version
      shell: bash
      run: |
        cd "${GITHUB_WORKSPACE}/actions"
        echo "##[set-output name=version;]$( python scripts/semver.py --patch )"
      id: get_version
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v2
    - name: check if version variable is set
      shell: bash
      run: |
        if [[ -z ${{ steps.get_version.outputs.version }} ]]; then
          echo "Error: version in environment is not set." 1>&2
          exit 1
        fi
        cd "${GITHUB_WORKSPACE}/actions"
        cat version.json
    - name: git add, commit and push
      shell: bash
      run: |
        cd "${GITHUB_WORKSPACE}/actions"
        git config user.email git.action@gft.com
        git config user.name "git.action"
        git add version.json
        git commit -m "Add version.json"
        git tag -a "internal-v${{ steps.semver.outputs.version }}" -m "semver tagging ${{ steps.semver.version }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ steps.server.outputs.branch }}
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: /home/runner/work/actions/actions
