# This workflow will run semver.pl and update the versions.json file in the root folder.
# The version.jsonfile is then added, commited and pushed to the current branch.

name: semver
#name: Houston Service - semver workflow

on:
  create

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Echo Branch Name
      shell: bash
      run: |
        echo Branch name: ${{ steps.extract_branch.outputs.branch }}

  
on:
  push:
    branches-ignore: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract current branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Echo Branch Name
      shell: bash
      run: |
        echo Branch name: ${{ steps.extract_branch.outputs.branch }}
    - uses: actions/checkout@v2
      with:
        #repository: tranquilitybase-io/tb-houston-service
        #repository: karwootang-gft/tb-houston-service
        repository: stugit/actions
        path: .
        fetch-depth: 0
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run semver, store in step variable version
      shell: bash
      run: |
        ls -alrt
        echo "##[set-output name=version;]$(python scripts/semver.py ${{ steps.extract_branch.outputs.branch }})"
      id: get_version
    - name: check if version variable is set
      shell: bash
      run: |
        if [[ -z ${{ steps.get_version.outputs.version }} ]]; then
          echo "Error: version in environment is not set." 1>&2
          exit 1
        fi
        cat version.json
    - name: git add, commit and push
      shell: bash
      run: |
        git config user.email git.action@gft.com
        git config user.name "git.action"
        git add version.json
        git commit -m "Add version.json"
        git tag -a "internal-v${{ steps.get_version.outputs.version }}" -m "semver tagging ${{ steps.get_version_outputs.version }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ steps.extract_branch.outputs.branch }}
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
