# This workflow will run semver.pl and update the versions.json file in the root folder.
# The version.jsonfile is then added, commited and pushed to the current branch.

name: semver

on:
  push

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
    - name: Extract current branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch
    - name: Echo Branch Name
      shell: bash
      run: |
        echo Branch name: ${{ steps.branch.outputs.branch }}

    - uses: actions/checkout@v2
      with:
        repository: stugit/actions
        path: actions
        fetch-depth: 0
  
    - name: run semver
      shell: bash
      run: |
        bash -x ${GITHUB_WORKSPACE}/actions/scripts/internal_semver.sh 
      env: 
        GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
        SOURCE: actions

#  tag:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@master
#      with:
#        fetch-depth: '0'
#    - name: Bump version and push tag
#      uses: anothrNick/github-tag-action@1.19.0
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        WITH_V: true
